#!/run/current-system/sw/bin/zsh

# Use zsh above because bash doesn't find the UTF-8 locales on NixOS which tmux needs

set -eu -o pipefail

# https://stackoverflow.com/a/12873723
function html_escape() {
    sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/"/\&quot;/g; s/'"'"'/\&#39;/g'
}

function linkify_log() {
	sed -r 's,^\[youtube\] (.{11}),[youtube] <a href="https://www.youtube.com/watch?v=\1" target="_blank">\1</a>,g' |\
	sed -r 's,^Skipping (.{11}) because,Skipping <a href="https://www.youtube.com/watch?v=\1" target="_blank">\1</a> because,g' |\
	sed -r 's,^\[youtube:playlist\] (.{24}):,[youtube:playlist] <a href="https://www.youtube.com/playlist?list=\1" target="_blank">\1</a>:,g' |\
	sed -r 's,^(ERROR: .*)$,<span class="error">\1</span>,g' |\
	sed -r 's,(^\[download\] Downloading video [0-9]+ of [0-9]+)$,<span class="download">\1</span>,g'
}

function url_for_identifier() {
	if [[ $1 == UC?????????????????????? ]]; then
		echo "https://www.youtube.com/channel/$1/videos"
	elif [[ $1 == PL* ]]; then
		echo "https://www.youtube.com/playlist?list=$1"
	else
		echo "https://www.youtube.com/user/$1/videos"
	fi
}

sessions=$(tmux list-sessions -F '#{session_created} #S' | grep -P '^\d+ YouTube-' | sort -rn)

echo "Content-Type: text/html; charset=utf-8

<style>

body {
	font-family: system-ui, sans-serif;
}

hr {
    border: none;
    height: 1px;
    background-color: #e1e1e1;
}

h1 {
	font-size: 18px;
	margin: 0 0 0 7px;
}

a {
	text-decoration: none;
}

pre {
	display: inline-block;
	border: 1px dotted #ccc;
	padding: 5px;
	margin: 0 0 1em 0;
}

span.error {
	color: #dd0000;
}

span.download {
	font-weight: bold;
}

</style>

$(echo $sessions | wc -l) downloaders running. Press F5 to refresh 🤷️
<hr>
"

tmux list-sessions -F '#{session_created} #S' | grep -P '^\d+ YouTube-' | sort -rn |\
while read line; do
	session_name=$(echo -E "$line" | cut -d ' ' -f 2)
	identifier=${session_name/YouTube-/}
	url=$(url_for_identifier "$identifier")
	echo "<h1><a name=\"$identifier\" href=\"$url\" target=\"_blank\">$identifier</a> (<a href=\"/logs/dl/$identifier/?C=M;O=D\" target=\"_blank\">logs</a>)</h1>"
	echo "<pre>"
	tmux capture-pane -p -t "$session_name" | html_escape | linkify_log
	echo "</pre>"
done

scripts=$(ps w | grep -P '[b]in/grab-.*-youtube$' | sort -n)

echo "<hr>\

$(echo $scripts | wc -l) scripts running:<br>

<pre>
$(echo $scripts | html_escape)
</pre>
"
